# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2809e87b85ef4fbaf4ad9da8d5367680167320df241e5a868db0dbb6d3966c2610d449aafa553ce40f81b36a2c505b6c0deb9c5e52a5680717b662fd25a9688

test:
  secret_key_base: 281b2debeb4e993e290ad9242c7b03ac0b992502e63f5a14a5f3f5f72635d4e9e3dd1b787b7ae7c57ecdd76864c12085c75e330dd7619957c01898d8c6314573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
